repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.9
  hooks:
    # Run the linter.
    - id: ruff
      stages: [pre-commit]
    # Run the formatter.
    - id: ruff-format
      stages: [pre-commit]
- repo: local
  hooks:
    - id: pytest
      name: pytest
      entry: uv run pytest
      language: system
      pass_filenames: false
      stages: [pre-merge-commit]