"""fix relationships

Revision ID: 0cd437bda9b8
Revises: ce72fcca9378
Create Date: 2025-06-08 15:16:03.882450

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0cd437bda9b8"
down_revision: Union[str, None] = "ce72fcca9378"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("password", sa.String(), nullable=False), schema="dev")
    op.drop_column("user", "pasword", schema="dev")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("pasword", sa.VARCHAR(), autoincrement=False, nullable=False),
        schema="dev",
    )
    op.drop_column("user", "password", schema="dev")
    # ### end Alembic commands ###
