"""rename extract to sponsorship

Revision ID: 0fc84833d866
Revises: 49855a32c5f9
Create Date: 2025-06-12 17:11:14.782828

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0fc84833d866"
down_revision: Union[str, None] = "49855a32c5f9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sponsorship",
        sa.Column("sponsor_name", sa.String(), nullable=False),
        sa.Column("sponsor_description", sa.String(), nullable=False),
        sa.Column("sponsor_offer", sa.String(), nullable=True),
        sa.Column("sponsor_code", sa.String(), nullable=True),
        sa.Column("sponsor_links", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("segment_id", sa.UUID(), nullable=False),
        sa.Column("sponsor_id", sa.UUID(), nullable=True),
        sa.Column("checked_extract", sa.Boolean(), nullable=False),
        sa.Column("confirmed_extract", sa.Boolean(), nullable=False),
        sa.Column("checked_match", sa.Boolean(), nullable=False),
        sa.Column("confirmed_match", sa.Boolean(), nullable=False),
        sa.Column("model_used", sa.String(), nullable=True),
        sa.Column("model_api", sa.String(), nullable=True),
        sa.Column("model_provider", sa.String(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["segment_id"],
            ["dev.segment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sponsor_id"],
            ["dev.sponsor.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="dev",
    )
    op.create_index(op.f("ix_dev_sponsorship_id"), "sponsorship", ["id"], unique=True, schema="dev")
    op.create_index(
        op.f("ix_dev_sponsorship_model_api"),
        "sponsorship",
        ["model_api"],
        unique=False,
        schema="dev",
    )
    op.create_index(
        op.f("ix_dev_sponsorship_model_provider"),
        "sponsorship",
        ["model_provider"],
        unique=False,
        schema="dev",
    )
    op.create_index(
        op.f("ix_dev_sponsorship_model_used"),
        "sponsorship",
        ["model_used"],
        unique=False,
        schema="dev",
    )
    op.create_index(
        op.f("ix_dev_sponsorship_segment_id"),
        "sponsorship",
        ["segment_id"],
        unique=False,
        schema="dev",
    )
    op.create_index(
        op.f("ix_dev_sponsorship_sponsor_id"),
        "sponsorship",
        ["sponsor_id"],
        unique=False,
        schema="dev",
    )
    op.create_index(
        op.f("ix_dev_sponsorship_sponsor_name"),
        "sponsorship",
        ["sponsor_name"],
        unique=False,
        schema="dev",
    )
    op.drop_index(op.f("ix_dev_extract_id"), table_name="extract", schema="dev")
    op.drop_index(op.f("ix_dev_extract_model_api"), table_name="extract", schema="dev")
    op.drop_index(op.f("ix_dev_extract_model_provider"), table_name="extract", schema="dev")
    op.drop_index(op.f("ix_dev_extract_model_used"), table_name="extract", schema="dev")
    op.drop_index(op.f("ix_dev_extract_segment_id"), table_name="extract", schema="dev")
    op.drop_index(op.f("ix_dev_extract_sponsor_id"), table_name="extract", schema="dev")
    op.drop_index(op.f("ix_dev_extract_sponsor_name"), table_name="extract", schema="dev")
    op.drop_table("extract", schema="dev")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "extract",
        sa.Column("sponsor_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("sponsor_description", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("sponsor_offer", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("sponsor_code", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "sponsor_links", postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True
        ),
        sa.Column("segment_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("sponsor_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("checked_extract", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("confirmed_extract", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("checked_match", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("confirmed_match", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("model_used", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("model_api", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("model_provider", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["segment_id"], ["dev.segment.id"], name=op.f("extract_segment_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["sponsor_id"], ["dev.sponsor.id"], name=op.f("extract_sponsor_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("extract_pkey")),
        schema="dev",
    )
    op.create_index(
        op.f("ix_dev_extract_sponsor_name"), "extract", ["sponsor_name"], unique=False, schema="dev"
    )
    op.create_index(
        op.f("ix_dev_extract_sponsor_id"), "extract", ["sponsor_id"], unique=False, schema="dev"
    )
    op.create_index(
        op.f("ix_dev_extract_segment_id"), "extract", ["segment_id"], unique=False, schema="dev"
    )
    op.create_index(
        op.f("ix_dev_extract_model_used"), "extract", ["model_used"], unique=False, schema="dev"
    )
    op.create_index(
        op.f("ix_dev_extract_model_provider"),
        "extract",
        ["model_provider"],
        unique=False,
        schema="dev",
    )
    op.create_index(
        op.f("ix_dev_extract_model_api"), "extract", ["model_api"], unique=False, schema="dev"
    )
    op.create_index(op.f("ix_dev_extract_id"), "extract", ["id"], unique=True, schema="dev")
    op.drop_index(op.f("ix_dev_sponsorship_sponsor_name"), table_name="sponsorship", schema="dev")
    op.drop_index(op.f("ix_dev_sponsorship_sponsor_id"), table_name="sponsorship", schema="dev")
    op.drop_index(op.f("ix_dev_sponsorship_segment_id"), table_name="sponsorship", schema="dev")
    op.drop_index(op.f("ix_dev_sponsorship_model_used"), table_name="sponsorship", schema="dev")
    op.drop_index(op.f("ix_dev_sponsorship_model_provider"), table_name="sponsorship", schema="dev")
    op.drop_index(op.f("ix_dev_sponsorship_model_api"), table_name="sponsorship", schema="dev")
    op.drop_index(op.f("ix_dev_sponsorship_id"), table_name="sponsorship", schema="dev")
    op.drop_table("sponsorship", schema="dev")
    # ### end Alembic commands ###
