"""fix fk metadata

Revision ID: 102008005073
Revises: 1a9c834127ab
Create Date: 2025-06-15 23:47:34.360316

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "102008005073"
down_revision: Union[str, None] = "1a9c834127ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_dev_video_video_metadata_id"), table_name="video", schema="dev")
    op.drop_constraint(
        op.f("video_video_metadata_id_fkey"), "video", schema="dev", type_="foreignkey"
    )
    op.drop_column("video", "video_metadata_id", schema="dev")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "video",
        sa.Column("video_metadata_id", sa.UUID(), autoincrement=False, nullable=True),
        schema="dev",
    )
    op.create_foreign_key(
        op.f("video_video_metadata_id_fkey"),
        "video",
        "videometadata",
        ["video_metadata_id"],
        ["id"],
        source_schema="dev",
        referent_schema="dev",
    )
    op.create_index(
        op.f("ix_dev_video_video_metadata_id"),
        "video",
        ["video_metadata_id"],
        unique=False,
        schema="dev",
    )
    # ### end Alembic commands ###
