"""add flag

Revision ID: 117975c15721
Revises:
Create Date: 2025-06-28 22:30:04.351080

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "117975c15721"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "flag",
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("entity_flagged", sa.String(), nullable=False),
        sa.Column("flagged_field", sa.String(), nullable=False),
        sa.Column("current_value", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="dev",
    )
    op.create_index(
        op.f("ix_dev_flag_entity_flagged"), "flag", ["entity_flagged"], unique=False, schema="dev"
    )
    op.create_index(
        op.f("ix_dev_flag_entity_id"), "flag", ["entity_id"], unique=False, schema="dev"
    )
    op.create_index(
        op.f("ix_dev_flag_flagged_field"), "flag", ["flagged_field"], unique=False, schema="dev"
    )
    op.create_index(op.f("ix_dev_flag_id"), "flag", ["id"], unique=True, schema="dev")
    op.create_index(op.f("ix_dev_flag_status"), "flag", ["status"], unique=False, schema="dev")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_dev_flag_status"), table_name="flag", schema="dev")
    op.drop_index(op.f("ix_dev_flag_id"), table_name="flag", schema="dev")
    op.drop_index(op.f("ix_dev_flag_flagged_field"), table_name="flag", schema="dev")
    op.drop_index(op.f("ix_dev_flag_entity_id"), table_name="flag", schema="dev")
    op.drop_index(op.f("ix_dev_flag_entity_flagged"), table_name="flag", schema="dev")
    op.drop_table("flag", schema="dev")
    # ### end Alembic commands ###
