"""add videometadata

Revision ID: 1a9c834127ab
Revises: 69dd25143b3e
Create Date: 2025-06-15 23:43:38.335189

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1a9c834127ab"
down_revision: Union[str, None] = "69dd25143b3e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "videometadata",
        sa.Column("raw_json", sa.JSON(), nullable=False),
        sa.Column("raw_transcript", sa.JSON(), nullable=True),
        sa.Column("video_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["dev.video.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="dev",
    )
    op.create_index(
        op.f("ix_dev_videometadata_id"), "videometadata", ["id"], unique=True, schema="dev"
    )
    op.create_index(
        op.f("ix_dev_videometadata_video_id"),
        "videometadata",
        ["video_id"],
        unique=False,
        schema="dev",
    )
    op.add_column("video", sa.Column("video_metadata_id", sa.UUID(), nullable=True), schema="dev")
    op.create_index(
        op.f("ix_dev_video_video_metadata_id"),
        "video",
        ["video_metadata_id"],
        unique=False,
        schema="dev",
    )
    op.create_foreign_key(
        None,
        "video",
        "videometadata",
        ["video_metadata_id"],
        ["id"],
        source_schema="dev",
        referent_schema="dev",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "video", schema="dev", type_="foreignkey")
    op.drop_index(op.f("ix_dev_video_video_metadata_id"), table_name="video", schema="dev")
    op.drop_column("video", "video_metadata_id", schema="dev")
    op.drop_index(op.f("ix_dev_videometadata_video_id"), table_name="videometadata", schema="dev")
    op.drop_index(op.f("ix_dev_videometadata_id"), table_name="videometadata", schema="dev")
    op.drop_table("videometadata", schema="dev")
    # ### end Alembic commands ###
