"""remove duration from sponsored segment

Revision ID: 1ef882c91f7b
Revises: 0385449d7ae5
Create Date: 2025-07-08 19:51:55.369021

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "1ef882c91f7b"
down_revision: Union[str, None] = "0385449d7ae5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sponsoredsegment", "duration", schema="dev")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sponsoredsegment", sa.Column("duration", sa.Float(), nullable=True), schema="dev"
    )
    # ### end Alembic commands ###
