"""add sponsorship table

Revision ID: 2fbe7ad7f36b
Revises: 4850fb1d6d04
Create Date: 2025-06-17 20:52:53.388369

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2fbe7ad7f36b"
down_revision: Union[str, None] = "4850fb1d6d04"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sponsorship",
        sa.Column("sponsor_name", sa.String(), nullable=False),
        sa.Column("sponsor_description", sa.String(), nullable=True),
        sa.Column("sponsor_links", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("sponsor_coupon_code", sa.String(), nullable=True),
        sa.Column("sponsor_offer", sa.String(), nullable=True),
        sa.Column("sponsored_segment_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sponsored_segment_id"],
            ["dev.sponsoredsegment.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="dev",
    )
    op.create_index(op.f("ix_dev_sponsorship_id"), "sponsorship", ["id"], unique=True, schema="dev")
    op.create_index(
        op.f("ix_dev_sponsorship_sponsored_segment_id"),
        "sponsorship",
        ["sponsored_segment_id"],
        unique=False,
        schema="dev",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_dev_sponsorship_sponsored_segment_id"), table_name="sponsorship", schema="dev"
    )
    op.drop_index(op.f("ix_dev_sponsorship_id"), table_name="sponsorship", schema="dev")
    op.drop_table("sponsorship", schema="dev")
    # ### end Alembic commands ###
