"""remove uploader_id field from video

Revision ID: 4850fb1d6d04
Revises: 102008005073
Create Date: 2025-06-16 18:35:12.497984

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4850fb1d6d04"
down_revision: Union[str, None] = "102008005073"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("video", "uploader_id", schema="dev")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "video",
        sa.Column("uploader_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        schema="dev",
    )
    # ### end Alembic commands ###
