"""remove username field

Revision ID: 49855a32c5f9
Revises: 60e7eb422285
Create Date: 2025-06-10 17:45:55.777074

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "49855a32c5f9"
down_revision: Union[str, None] = "60e7eb422285"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("user_username_key"), "user", schema="dev", type_="unique")
    op.drop_index(op.f("ix_dev_user_email"), table_name="user", schema="dev")
    op.create_index(op.f("ix_dev_user_email"), "user", ["email"], unique=True, schema="dev")
    op.drop_column("user", "username", schema="dev")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("username", sa.VARCHAR(), autoincrement=False, nullable=False),
        schema="dev",
    )
    op.drop_index(op.f("ix_dev_user_email"), table_name="user", schema="dev")
    op.create_index(op.f("ix_dev_user_email"), "user", ["email"], unique=False, schema="dev")
    op.create_unique_constraint(
        op.f("user_username_key"),
        "user",
        ["username"],
        schema="dev",
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
