"""edit flag column names

Revision ID: 49cb107f27be
Revises: 117975c15721
Create Date: 2025-06-28 22:34:38.739263

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "49cb107f27be"
down_revision: Union[str, None] = "117975c15721"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("flag", sa.Column("field_flagged", sa.String(), nullable=False), schema="dev")
    op.add_column("flag", sa.Column("value_flagged", sa.JSON(), nullable=True), schema="dev")
    op.drop_index(op.f("ix_dev_flag_flagged_field"), table_name="flag", schema="dev")
    op.create_index(
        op.f("ix_dev_flag_field_flagged"), "flag", ["field_flagged"], unique=False, schema="dev"
    )
    op.drop_column("flag", "current_value", schema="dev")
    op.drop_column("flag", "flagged_field", schema="dev")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "flag",
        sa.Column("flagged_field", sa.VARCHAR(), autoincrement=False, nullable=False),
        schema="dev",
    )
    op.add_column(
        "flag",
        sa.Column(
            "current_value",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        schema="dev",
    )
    op.drop_index(op.f("ix_dev_flag_field_flagged"), table_name="flag", schema="dev")
    op.create_index(
        op.f("ix_dev_flag_flagged_field"), "flag", ["flagged_field"], unique=False, schema="dev"
    )
    op.drop_column("flag", "value_flagged", schema="dev")
    op.drop_column("flag", "field_flagged", schema="dev")
    # ### end Alembic commands ###
