"""fix sponsorship_id relationship

Revision ID: 4d4fff8e0f1d
Revises: a5f5860899a4
Create Date: 2025-06-22 18:33:26.463509

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "4d4fff8e0f1d"
down_revision: Union[str, None] = "a5f5860899a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("generatedsponsorship_sponsorship_id_fkey"),
        "generatedsponsorship",
        schema="dev",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "generatedsponsorship",
        "sponsorship",
        ["sponsorship_id"],
        ["id"],
        source_schema="dev",
        referent_schema="dev",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "generatedsponsorship", schema="dev", type_="foreignkey")
    op.create_foreign_key(
        op.f("generatedsponsorship_sponsorship_id_fkey"),
        "generatedsponsorship",
        "sponsoredsegment",
        ["sponsorship_id"],
        ["id"],
        source_schema="dev",
        referent_schema="dev",
    )
    # ### end Alembic commands ###
