"""fix accesstoken user relationship

Revision ID: 4feee792858a
Revises: c33b8f0837f1
Create Date: 2025-06-08 14:56:32.638844

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "4feee792858a"
down_revision: Union[str, None] = "c33b8f0837f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("accesstoken_user_id_fkey"), "accesstoken", schema="dev", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "accesstoken", "user", ["user_id"], ["id"], source_schema="dev", referent_schema="dev"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "accesstoken", schema="dev", type_="foreignkey")
    op.create_foreign_key(
        op.f("accesstoken_user_id_fkey"),
        "accesstoken",
        "accesstoken",
        ["user_id"],
        ["id"],
        source_schema="dev",
        referent_schema="dev",
    )
    # ### end Alembic commands ###
