"""add video and sponsored_segment

Revision ID: 52661e345870
Revises:
Create Date: 2025-06-14 14:47:04.543637

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "52661e345870"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "video",
        sa.Column("youtube_id", sa.String(), nullable=False),
        sa.Column("language", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("uploader_id", sa.String(), nullable=False),
        sa.Column("upload_date", sa.Date(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("duration", sa.Float(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("youtube_id"),
        schema="dev",
    )
    op.create_index(op.f("ix_dev_video_id"), "video", ["id"], unique=True, schema="dev")
    op.create_index(
        op.f("ix_dev_video_language"), "video", ["language"], unique=False, schema="dev"
    )
    op.create_table(
        "sponsoredsegment",
        sa.Column("sponsorblock_id", sa.String(), nullable=True),
        sa.Column("start_time", sa.Float(), nullable=False),
        sa.Column("end_time", sa.Float(), nullable=False),
        sa.Column("subtitles", sa.String(), nullable=False),
        sa.Column("duration", sa.Float(), nullable=False),
        sa.Column("parent_video_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_video_id"],
            ["dev.video.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sponsorblock_id"),
        schema="dev",
    )
    op.create_index(
        op.f("ix_dev_sponsoredsegment_id"), "sponsoredsegment", ["id"], unique=True, schema="dev"
    )
    op.create_index(
        op.f("ix_dev_sponsoredsegment_parent_video_id"),
        "sponsoredsegment",
        ["parent_video_id"],
        unique=False,
        schema="dev",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_dev_sponsoredsegment_parent_video_id"), table_name="sponsoredsegment", schema="dev"
    )
    op.drop_index(op.f("ix_dev_sponsoredsegment_id"), table_name="sponsoredsegment", schema="dev")
    op.drop_table("sponsoredsegment", schema="dev")
    op.drop_index(op.f("ix_dev_video_language"), table_name="video", schema="dev")
    op.drop_index(op.f("ix_dev_video_id"), table_name="video", schema="dev")
    op.drop_table("video", schema="dev")
    # ### end Alembic commands ###
