"""add superuser and validated fields to user

Revision ID: 60e7eb422285
Revises: e2f1a50ba1cd
Create Date: 2025-06-08 21:17:48.522511

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "60e7eb422285"
down_revision: Union[str, None] = "e2f1a50ba1cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("is_superuser", sa.Boolean(), nullable=True), schema="dev")
    op.execute('UPDATE dev."user" SET is_superuser = FALSE')
    op.alter_column("user", "is_superuser", nullable=False, schema="dev")
    op.add_column("user", sa.Column("is_verified", sa.Boolean(), nullable=True), schema="dev")
    op.execute('UPDATE dev."user" SET is_verified = FALSE')
    op.alter_column("user", "is_verified", nullable=False, schema="dev")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_verified", schema="dev")
    op.drop_column("user", "is_superuser", schema="dev")
    # ### end Alembic commands ###
