"""nullable video fields

Revision ID: 69dd25143b3e
Revises: ab5dfea01f4e
Create Date: 2025-06-14 16:31:22.358959

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "69dd25143b3e"
down_revision: Union[str, None] = "ab5dfea01f4e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("video", "language", existing_type=sa.VARCHAR(), nullable=True, schema="dev")
    op.alter_column("video", "title", existing_type=sa.VARCHAR(), nullable=True, schema="dev")
    op.alter_column("video", "uploader_id", existing_type=sa.VARCHAR(), nullable=True, schema="dev")
    op.alter_column("video", "upload_date", existing_type=sa.DATE(), nullable=True, schema="dev")
    op.alter_column("video", "description", existing_type=sa.VARCHAR(), nullable=True, schema="dev")
    op.alter_column(
        "video",
        "duration",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
        schema="dev",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "video",
        "duration",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
        schema="dev",
    )
    op.alter_column(
        "video", "description", existing_type=sa.VARCHAR(), nullable=False, schema="dev"
    )
    op.alter_column("video", "upload_date", existing_type=sa.DATE(), nullable=False, schema="dev")
    op.alter_column(
        "video", "uploader_id", existing_type=sa.VARCHAR(), nullable=False, schema="dev"
    )
    op.alter_column("video", "title", existing_type=sa.VARCHAR(), nullable=False, schema="dev")
    op.alter_column("video", "language", existing_type=sa.VARCHAR(), nullable=False, schema="dev")
    # ### end Alembic commands ###
