"""rename sponsorship to generatedsponsorship

Revision ID: 6a0c33a78e70
Revises: cb136460ed24
Create Date: 2025-06-22 14:09:11.511652

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6a0c33a78e70"
down_revision: Union[str, None] = "cb136460ed24"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("sponsorship", "generatedsponsorship", schema="dev")
    op.drop_index("ix_dev_sponsorship_id", table_name="generatedsponsorship", schema="dev")
    op.drop_index(
        "ix_dev_sponsorship_sponsored_segment_id", table_name="generatedsponsorship", schema="dev"
    )
    op.create_index(
        "ix_dev_generatedsponsorship_id", "generatedsponsorship", ["id"], unique=True, schema="dev"
    )
    op.create_index(
        "ix_dev_generatedsponsorship_sponsored_segment_id",
        "generatedsponsorship",
        ["sponsored_segment_id"],
        unique=True,
        schema="dev",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_dev_generatedsponsorship_id", table_name="generatedsponsorship", schema="dev")
    op.drop_index(
        "ix_dev_generatedsponsorship_sponsored_segment_id",
        table_name="generatedsponsorship",
        schema="dev",
    )
    op.rename_table("generatedsponsorship", "sponsorship", schema="dev")
    op.create_index("ix_dev_sponsorship_id", "sponsorship", ["id"], unique=True, schema="dev")
    op.create_index(
        "ix_dev_sponsorship_sponsored_segment_id",
        "sponsorship",
        ["sponsored_segment_id"],
        unique=True,
        schema="dev",
    )
    # ### end Alembic commands ###
