"""split sponsorships into 3 tables

Revision ID: 6bcc36dc4489
Revises: 6a0c33a78e70
Create Date: 2025-06-22 14:42:54.498382

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6bcc36dc4489"
down_revision: Union[str, None] = "6a0c33a78e70"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sponsorship",
        sa.Column("sponsor_name", sa.String(), nullable=False),
        sa.Column("sponsor_description", sa.String(), nullable=True),
        sa.Column("sponsor_links", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("sponsor_coupon_code", sa.String(), nullable=True),
        sa.Column("sponsor_offer", sa.String(), nullable=True),
        sa.Column("sponsored_segment_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sponsored_segment_id"],
            ["dev.sponsoredsegment.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="dev",
    )
    op.create_index(op.f("ix_dev_sponsorship_id"), "sponsorship", ["id"], unique=True, schema="dev")
    op.create_index(
        op.f("ix_dev_sponsorship_sponsored_segment_id"),
        "sponsorship",
        ["sponsored_segment_id"],
        unique=False,
        schema="dev",
    )
    op.create_table(
        "sponsorshipflag",
        sa.Column("flagged_field", sa.String(), nullable=False),
        sa.Column("correction", sa.String(), nullable=True),
        sa.Column("generated_sponsorship_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["generated_sponsorship_id"],
            ["dev.generatedsponsorship.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="dev",
    )
    op.create_index(
        op.f("ix_dev_sponsorshipflag_generated_sponsorship_id"),
        "sponsorshipflag",
        ["generated_sponsorship_id"],
        unique=False,
        schema="dev",
    )
    op.create_index(
        op.f("ix_dev_sponsorshipflag_id"), "sponsorshipflag", ["id"], unique=True, schema="dev"
    )
    op.add_column(
        "generatedsponsorship", sa.Column("sponsorship_id", sa.UUID(), nullable=True), schema="dev"
    )
    op.drop_index(
        op.f("ix_dev_generatedsponsorship_sponsored_segment_id"),
        table_name="generatedsponsorship",
        schema="dev",
    )
    op.create_index(
        op.f("ix_dev_generatedsponsorship_sponsorship_id"),
        "generatedsponsorship",
        ["sponsorship_id"],
        unique=False,
        schema="dev",
    )
    op.drop_constraint(
        op.f("sponsorship_sponsored_segment_id_fkey"),
        "generatedsponsorship",
        schema="dev",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "generatedsponsorship",
        "sponsoredsegment",
        ["sponsorship_id"],
        ["id"],
        source_schema="dev",
        referent_schema="dev",
    )
    op.drop_column("generatedsponsorship", "sponsored_segment_id", schema="dev")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "generatedsponsorship",
        sa.Column("sponsored_segment_id", sa.UUID(), autoincrement=False, nullable=False),
        schema="dev",
    )
    op.drop_constraint(None, "generatedsponsorship", schema="dev", type_="foreignkey")
    op.create_foreign_key(
        op.f("sponsorship_sponsored_segment_id_fkey"),
        "generatedsponsorship",
        "sponsoredsegment",
        ["sponsored_segment_id"],
        ["id"],
        source_schema="dev",
        referent_schema="dev",
    )
    op.drop_index(
        op.f("ix_dev_generatedsponsorship_sponsorship_id"),
        table_name="generatedsponsorship",
        schema="dev",
    )
    op.create_index(
        op.f("ix_dev_generatedsponsorship_sponsored_segment_id"),
        "generatedsponsorship",
        ["sponsored_segment_id"],
        unique=True,
        schema="dev",
    )
    op.drop_column("generatedsponsorship", "sponsorship_id", schema="dev")
    op.drop_index(op.f("ix_dev_sponsorshipflag_id"), table_name="sponsorshipflag", schema="dev")
    op.drop_index(
        op.f("ix_dev_sponsorshipflag_generated_sponsorship_id"),
        table_name="sponsorshipflag",
        schema="dev",
    )
    op.drop_table("sponsorshipflag", schema="dev")
    op.drop_index(
        op.f("ix_dev_sponsorship_sponsored_segment_id"), table_name="sponsorship", schema="dev"
    )
    op.drop_index(op.f("ix_dev_sponsorship_id"), table_name="sponsorship", schema="dev")
    op.drop_table("sponsorship", schema="dev")
    # ### end Alembic commands ###
