"""fresh migration

Revision ID: 6d61ab25cda8
Revises:
Create Date: 2025-06-22 18:42:41.034249

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "6d61ab25cda8"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
