"""initial migration

Revision ID: 86143cab6110
Revises:
Create Date: 2025-06-07 23:14:28.928885

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "86143cab6110"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accesstoken",
        sa.Column("token_hash", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["dev.accesstoken.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="dev",
    )
    op.create_index(
        op.f("ix_dev_accesstoken_id"), "accesstoken", ["id"], unique=False, schema="dev"
    )
    op.create_index(
        op.f("ix_dev_accesstoken_revoked"), "accesstoken", ["revoked"], unique=False, schema="dev"
    )
    op.create_index(
        op.f("ix_dev_accesstoken_user_id"), "accesstoken", ["user_id"], unique=False, schema="dev"
    )
    op.create_table(
        "channel",
        sa.Column("youtube_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("handle", sa.String(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="dev",
    )
    op.create_index(
        op.f("ix_dev_channel_handle"), "channel", ["handle"], unique=False, schema="dev"
    )
    op.create_index(op.f("ix_dev_channel_id"), "channel", ["id"], unique=False, schema="dev")
    op.create_index(
        op.f("ix_dev_channel_youtube_id"), "channel", ["youtube_id"], unique=True, schema="dev"
    )
    op.create_table(
        "sponsor",
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="dev",
    )
    op.create_index(op.f("ix_dev_sponsor_id"), "sponsor", ["id"], unique=False, schema="dev")
    op.create_index(op.f("ix_dev_sponsor_name"), "sponsor", ["name"], unique=False, schema="dev")
    op.create_table(
        "user",
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("pasword", sa.String(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
        schema="dev",
    )
    op.create_index(op.f("ix_dev_user_email"), "user", ["email"], unique=False, schema="dev")
    op.create_index(op.f("ix_dev_user_id"), "user", ["id"], unique=False, schema="dev")
    op.create_table(
        "video",
        sa.Column("youtube_id", sa.String(), nullable=False),
        sa.Column("language", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("channel_id", sa.UUID(), nullable=False),
        sa.Column("uploader_id", sa.String(), nullable=False),
        sa.Column("upload_date", sa.Date(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("duration", sa.Float(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["dev.channel.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("youtube_id"),
        schema="dev",
    )
    op.create_index(
        op.f("ix_dev_video_channel_id"), "video", ["channel_id"], unique=False, schema="dev"
    )
    op.create_index(op.f("ix_dev_video_id"), "video", ["id"], unique=False, schema="dev")
    op.create_index(
        op.f("ix_dev_video_language"), "video", ["language"], unique=False, schema="dev"
    )
    op.create_table(
        "segment",
        sa.Column("sponsorblock_id", sa.String(), nullable=True),
        sa.Column("start_time", sa.Float(), nullable=False),
        sa.Column("end_time", sa.Float(), nullable=False),
        sa.Column("subtitles", sa.String(), nullable=False),
        sa.Column("duration", sa.Float(), nullable=False),
        sa.Column("parent_video_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_video_id"],
            ["dev.video.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="dev",
    )
    op.create_index(op.f("ix_dev_segment_id"), "segment", ["id"], unique=False, schema="dev")
    op.create_index(
        op.f("ix_dev_segment_parent_video_id"),
        "segment",
        ["parent_video_id"],
        unique=False,
        schema="dev",
    )
    op.create_table(
        "extract",
        sa.Column("sponsor_name", sa.String(), nullable=False),
        sa.Column("sponsor_description", sa.String(), nullable=False),
        sa.Column("sponsor_offer", sa.String(), nullable=True),
        sa.Column("sponsor_code", sa.String(), nullable=True),
        sa.Column("sponsor_links", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("segment_id", sa.UUID(), nullable=False),
        sa.Column("sponsor_id", sa.UUID(), nullable=True),
        sa.Column("checked_extract", sa.Boolean(), nullable=False),
        sa.Column("confirmed_extract", sa.Boolean(), nullable=False),
        sa.Column("checked_match", sa.Boolean(), nullable=False),
        sa.Column("confirmed_match", sa.Boolean(), nullable=False),
        sa.Column("model_used", sa.String(), nullable=True),
        sa.Column("model_api", sa.String(), nullable=True),
        sa.Column("model_provider", sa.String(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["segment_id"],
            ["dev.segment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sponsor_id"],
            ["dev.sponsor.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="dev",
    )
    op.create_index(op.f("ix_dev_extract_id"), "extract", ["id"], unique=False, schema="dev")
    op.create_index(
        op.f("ix_dev_extract_model_api"), "extract", ["model_api"], unique=False, schema="dev"
    )
    op.create_index(
        op.f("ix_dev_extract_model_provider"),
        "extract",
        ["model_provider"],
        unique=False,
        schema="dev",
    )
    op.create_index(
        op.f("ix_dev_extract_model_used"), "extract", ["model_used"], unique=False, schema="dev"
    )
    op.create_index(
        op.f("ix_dev_extract_segment_id"), "extract", ["segment_id"], unique=False, schema="dev"
    )
    op.create_index(
        op.f("ix_dev_extract_sponsor_id"), "extract", ["sponsor_id"], unique=False, schema="dev"
    )
    op.create_index(
        op.f("ix_dev_extract_sponsor_name"), "extract", ["sponsor_name"], unique=False, schema="dev"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_dev_extract_sponsor_name"), table_name="extract", schema="dev")
    op.drop_index(op.f("ix_dev_extract_sponsor_id"), table_name="extract", schema="dev")
    op.drop_index(op.f("ix_dev_extract_segment_id"), table_name="extract", schema="dev")
    op.drop_index(op.f("ix_dev_extract_model_used"), table_name="extract", schema="dev")
    op.drop_index(op.f("ix_dev_extract_model_provider"), table_name="extract", schema="dev")
    op.drop_index(op.f("ix_dev_extract_model_api"), table_name="extract", schema="dev")
    op.drop_index(op.f("ix_dev_extract_id"), table_name="extract", schema="dev")
    op.drop_table("extract", schema="dev")
    op.drop_index(op.f("ix_dev_segment_parent_video_id"), table_name="segment", schema="dev")
    op.drop_index(op.f("ix_dev_segment_id"), table_name="segment", schema="dev")
    op.drop_table("segment", schema="dev")
    op.drop_index(op.f("ix_dev_video_language"), table_name="video", schema="dev")
    op.drop_index(op.f("ix_dev_video_id"), table_name="video", schema="dev")
    op.drop_index(op.f("ix_dev_video_channel_id"), table_name="video", schema="dev")
    op.drop_table("video", schema="dev")
    op.drop_index(op.f("ix_dev_user_id"), table_name="user", schema="dev")
    op.drop_index(op.f("ix_dev_user_email"), table_name="user", schema="dev")
    op.drop_table("user", schema="dev")
    op.drop_index(op.f("ix_dev_sponsor_name"), table_name="sponsor", schema="dev")
    op.drop_index(op.f("ix_dev_sponsor_id"), table_name="sponsor", schema="dev")
    op.drop_table("sponsor", schema="dev")
    op.drop_index(op.f("ix_dev_channel_youtube_id"), table_name="channel", schema="dev")
    op.drop_index(op.f("ix_dev_channel_id"), table_name="channel", schema="dev")
    op.drop_index(op.f("ix_dev_channel_handle"), table_name="channel", schema="dev")
    op.drop_table("channel", schema="dev")
    op.drop_index(op.f("ix_dev_accesstoken_user_id"), table_name="accesstoken", schema="dev")
    op.drop_index(op.f("ix_dev_accesstoken_revoked"), table_name="accesstoken", schema="dev")
    op.drop_index(op.f("ix_dev_accesstoken_id"), table_name="accesstoken", schema="dev")
    op.drop_table("accesstoken", schema="dev")
    # ### end Alembic commands ###
