"""expand flag entity types

Revision ID: 993626339da8
Revises: 8730ba525c40
Create Date: 2025-07-01 09:09:39.607437

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "993626339da8"
down_revision: Union[str, None] = "8730ba525c40"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("COMMIT")
    op.execute("ALTER TYPE dev.entitytype ADD VALUE 'sponsored_segment'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE dev.entitytype RENAME TO dev.entitytype_old")
    op.execute("CREATE TYPE dev.entitytype AS ENUM('video', 'sponsorship')")
    op.execute(
        (
            "ALTER TABLE dev.flag ALTER COLUMN entity_flagged TYPE dev.entitytype USING "
            "entity_flagged::text::dev.entitytype"
        )
    )
    op.execute("DROP TYPE dev.entitytype_old")
    # ### end Alembic commands ###
