"""add value fields to flags

Revision ID: a5f5860899a4
Revises: f3247f48ae13
Create Date: 2025-06-22 16:46:13.829572

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a5f5860899a4"
down_revision: Union[str, None] = "f3247f48ae13"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sponsorshipflag", sa.Column("current_value", sa.String(), nullable=True), schema="dev"
    )
    op.add_column(
        "sponsorshipflag", sa.Column("corrected_value", sa.String(), nullable=True), schema="dev"
    )
    op.drop_column("sponsorshipflag", "correction", schema="dev")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sponsorshipflag",
        sa.Column("correction", sa.VARCHAR(), autoincrement=False, nullable=True),
        schema="dev",
    )
    op.drop_column("sponsorshipflag", "corrected_value", schema="dev")
    op.drop_column("sponsorshipflag", "current_value", schema="dev")
    # ### end Alembic commands ###
