"""make subtitles nullable

Revision ID: ab5dfea01f4e
Revises: 52661e345870
Create Date: 2025-06-14 15:14:14.258528

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ab5dfea01f4e"
down_revision: Union[str, None] = "52661e345870"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sponsoredsegment", "subtitles", existing_type=sa.VARCHAR(), nullable=True, schema="dev"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sponsoredsegment", "subtitles", existing_type=sa.VARCHAR(), nullable=False, schema="dev"
    )
    # ### end Alembic commands ###
