"""add videoflag sponsorshipflag

Revision ID: b29b6bd60669
Revises: 49cb107f27be
Create Date: 2025-06-29 10:13:56.890484

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b29b6bd60669"
down_revision: Union[str, None] = "49cb107f27be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    flagstatus_enum = sa.Enum("pending", "resolved", "dismissed", name="flagstatus", schema="dev")
    flagstatus_enum.create(op.get_bind(), checkfirst=True)

    op.add_column("flag", sa.Column("video_id", sa.UUID(), nullable=False), schema="dev")
    op.add_column("flag", sa.Column("sponsorship_id", sa.UUID(), nullable=False), schema="dev")
    op.execute("""
        ALTER TABLE dev.flag
        ALTER COLUMN status TYPE dev.flagstatus
        USING status::dev.flagstatus
    """)
    op.create_foreign_key(
        None,
        "flag",
        "sponsorship",
        ["sponsorship_id"],
        ["id"],
        source_schema="dev",
        referent_schema="dev",
    )
    op.create_foreign_key(
        None, "flag", "video", ["video_id"], ["id"], source_schema="dev", referent_schema="dev"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "flag", schema="dev", type_="foreignkey")
    op.drop_constraint(None, "flag", schema="dev", type_="foreignkey")
    op.execute("""
        ALTER TABLE dev.flag
        ALTER COLUMN status TYPE VARCHAR
        USING status::text
    """)
    sa.Enum(name="flagstatus", schema="dev").drop(op.get_bind(), checkfirst=True)
    op.drop_column("flag", "sponsorship_id", schema="dev")
    op.drop_column("flag", "video_id", schema="dev")
    # ### end Alembic commands ###
