"""unique pk ids

Revision ID: c33b8f0837f1
Revises: 86143cab6110
Create Date: 2025-06-07 23:34:23.046160

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "c33b8f0837f1"
down_revision: Union[str, None] = "86143cab6110"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_dev_accesstoken_id"), table_name="accesstoken", schema="dev")
    op.create_index(op.f("ix_dev_accesstoken_id"), "accesstoken", ["id"], unique=True, schema="dev")
    op.drop_index(op.f("ix_dev_channel_id"), table_name="channel", schema="dev")
    op.create_index(op.f("ix_dev_channel_id"), "channel", ["id"], unique=True, schema="dev")
    op.drop_index(op.f("ix_dev_extract_id"), table_name="extract", schema="dev")
    op.create_index(op.f("ix_dev_extract_id"), "extract", ["id"], unique=True, schema="dev")
    op.drop_index(op.f("ix_dev_segment_id"), table_name="segment", schema="dev")
    op.create_index(op.f("ix_dev_segment_id"), "segment", ["id"], unique=True, schema="dev")
    op.drop_index(op.f("ix_dev_sponsor_id"), table_name="sponsor", schema="dev")
    op.create_index(op.f("ix_dev_sponsor_id"), "sponsor", ["id"], unique=True, schema="dev")
    op.drop_index(op.f("ix_dev_user_id"), table_name="user", schema="dev")
    op.create_index(op.f("ix_dev_user_id"), "user", ["id"], unique=True, schema="dev")
    op.drop_index(op.f("ix_dev_video_id"), table_name="video", schema="dev")
    op.create_index(op.f("ix_dev_video_id"), "video", ["id"], unique=True, schema="dev")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_dev_video_id"), table_name="video", schema="dev")
    op.create_index(op.f("ix_dev_video_id"), "video", ["id"], unique=False, schema="dev")
    op.drop_index(op.f("ix_dev_user_id"), table_name="user", schema="dev")
    op.create_index(op.f("ix_dev_user_id"), "user", ["id"], unique=False, schema="dev")
    op.drop_index(op.f("ix_dev_sponsor_id"), table_name="sponsor", schema="dev")
    op.create_index(op.f("ix_dev_sponsor_id"), "sponsor", ["id"], unique=False, schema="dev")
    op.drop_index(op.f("ix_dev_segment_id"), table_name="segment", schema="dev")
    op.create_index(op.f("ix_dev_segment_id"), "segment", ["id"], unique=False, schema="dev")
    op.drop_index(op.f("ix_dev_extract_id"), table_name="extract", schema="dev")
    op.create_index(op.f("ix_dev_extract_id"), "extract", ["id"], unique=False, schema="dev")
    op.drop_index(op.f("ix_dev_channel_id"), table_name="channel", schema="dev")
    op.create_index(op.f("ix_dev_channel_id"), "channel", ["id"], unique=False, schema="dev")
    op.drop_index(op.f("ix_dev_accesstoken_id"), table_name="accesstoken", schema="dev")
    op.create_index(
        op.f("ix_dev_accesstoken_id"), "accesstoken", ["id"], unique=False, schema="dev"
    )
    # ### end Alembic commands ###
