"""add new columns to Sponsorship and Video

Revision ID: cb136460ed24
Revises: 2fbe7ad7f36b
Create Date: 2025-06-19 20:13:37.801400

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cb136460ed24"
down_revision: Union[str, None] = "2fbe7ad7f36b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sponsorship", sa.Column("generator", sa.String(), nullable=True), schema="dev")
    op.add_column("sponsorship", sa.Column("provider", sa.String(), nullable=True), schema="dev")
    op.add_column("sponsorship", sa.Column("model", sa.String(), nullable=True), schema="dev")
    op.add_column("video", sa.Column("channel", sa.String(), nullable=True), schema="dev")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("video", "channel", schema="dev")
    op.drop_column("sponsorship", "model", schema="dev")
    op.drop_column("sponsorship", "provider", schema="dev")
    op.drop_column("sponsorship", "generator", schema="dev")
    # ### end Alembic commands ###
