"""fix model imports

Revision ID: ce72fcca9378
Revises: 4feee792858a
Create Date: 2025-06-08 15:03:57.567706

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "ce72fcca9378"
down_revision: Union[str, None] = "4feee792858a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
