"""set default created_at and updated_at

Revision ID: e2f1a50ba1cd
Revises: 0cd437bda9b8
Create Date: 2025-06-08 15:40:25.503684

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e2f1a50ba1cd"
down_revision: Union[str, None] = "0cd437bda9b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "accesstoken",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("now()"),
        nullable=False,
        schema="dev",
    )
    op.alter_column(
        "accesstoken",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        schema="dev",
    )
    op.alter_column(
        "channel",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("now()"),
        nullable=False,
        schema="dev",
    )
    op.alter_column(
        "channel", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False, schema="dev"
    )
    op.alter_column(
        "extract",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("now()"),
        nullable=False,
        schema="dev",
    )
    op.alter_column(
        "extract", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False, schema="dev"
    )
    op.alter_column(
        "segment",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("now()"),
        nullable=False,
        schema="dev",
    )
    op.alter_column(
        "segment", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False, schema="dev"
    )
    op.alter_column(
        "sponsor",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("now()"),
        nullable=False,
        schema="dev",
    )
    op.alter_column(
        "sponsor", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False, schema="dev"
    )
    op.alter_column(
        "user",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("now()"),
        nullable=False,
        schema="dev",
    )
    op.alter_column(
        "user", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False, schema="dev"
    )
    op.alter_column(
        "video",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("now()"),
        nullable=False,
        schema="dev",
    )
    op.alter_column(
        "video", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False, schema="dev"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "video", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True, schema="dev"
    )
    op.alter_column(
        "video",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        nullable=True,
        schema="dev",
    )
    op.alter_column(
        "user", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True, schema="dev"
    )
    op.alter_column(
        "user",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        nullable=True,
        schema="dev",
    )
    op.alter_column(
        "sponsor", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True, schema="dev"
    )
    op.alter_column(
        "sponsor",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        nullable=True,
        schema="dev",
    )
    op.alter_column(
        "segment", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True, schema="dev"
    )
    op.alter_column(
        "segment",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        nullable=True,
        schema="dev",
    )
    op.alter_column(
        "extract", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True, schema="dev"
    )
    op.alter_column(
        "extract",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        nullable=True,
        schema="dev",
    )
    op.alter_column(
        "channel", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True, schema="dev"
    )
    op.alter_column(
        "channel",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        nullable=True,
        schema="dev",
    )
    op.alter_column(
        "accesstoken",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        schema="dev",
    )
    op.alter_column(
        "accesstoken",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        nullable=True,
        schema="dev",
    )
    # ### end Alembic commands ###
