"""change flag relationship to sponsorship

Revision ID: f3247f48ae13
Revises: 6bcc36dc4489
Create Date: 2025-06-22 16:43:25.770895

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f3247f48ae13"
down_revision: Union[str, None] = "6bcc36dc4489"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sponsorshipflag", sa.Column("status", sa.String(), nullable=True), schema="dev")
    op.add_column(
        "sponsorshipflag", sa.Column("sponsorship_id", sa.UUID(), nullable=False), schema="dev"
    )
    op.drop_index(
        op.f("ix_dev_sponsorshipflag_generated_sponsorship_id"),
        table_name="sponsorshipflag",
        schema="dev",
    )
    op.create_index(
        op.f("ix_dev_sponsorshipflag_sponsorship_id"),
        "sponsorshipflag",
        ["sponsorship_id"],
        unique=False,
        schema="dev",
    )
    op.drop_constraint(
        op.f("sponsorshipflag_generated_sponsorship_id_fkey"),
        "sponsorshipflag",
        schema="dev",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "sponsorshipflag",
        "sponsorship",
        ["sponsorship_id"],
        ["id"],
        source_schema="dev",
        referent_schema="dev",
    )
    op.drop_column("sponsorshipflag", "generated_sponsorship_id", schema="dev")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sponsorshipflag",
        sa.Column("generated_sponsorship_id", sa.UUID(), autoincrement=False, nullable=False),
        schema="dev",
    )
    op.drop_constraint(None, "sponsorshipflag", schema="dev", type_="foreignkey")
    op.create_foreign_key(
        op.f("sponsorshipflag_generated_sponsorship_id_fkey"),
        "sponsorshipflag",
        "generatedsponsorship",
        ["generated_sponsorship_id"],
        ["id"],
        source_schema="dev",
        referent_schema="dev",
    )
    op.drop_index(
        op.f("ix_dev_sponsorshipflag_sponsorship_id"), table_name="sponsorshipflag", schema="dev"
    )
    op.create_index(
        op.f("ix_dev_sponsorshipflag_generated_sponsorship_id"),
        "sponsorshipflag",
        ["generated_sponsorship_id"],
        unique=False,
        schema="dev",
    )
    op.drop_column("sponsorshipflag", "sponsorship_id", schema="dev")
    op.drop_column("sponsorshipflag", "status", schema="dev")
    # ### end Alembic commands ###
